// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6gOFisTQNEwHREZEgmE6BTrFq2gn6O1U',
    appId: '1:696086497678:web:a940de47ec08e6b016fcdf',
    messagingSenderId: '696086497678',
    projectId: 'ux-design-e1cd1',
    authDomain: 'ux-design-e1cd1.firebaseapp.com',
    storageBucket: 'ux-design-e1cd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD30XMe8GurtrR6V5Av2MSx87ON4NMzLS0',
    appId: '1:696086497678:android:82482f64cc9e456816fcdf',
    messagingSenderId: '696086497678',
    projectId: 'ux-design-e1cd1',
    storageBucket: 'ux-design-e1cd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsgsO6JTEpfJKJPGkOn-fm07wXVFfMum4',
    appId: '1:696086497678:ios:1d71a5b3b49b02fd16fcdf',
    messagingSenderId: '696086497678',
    projectId: 'ux-design-e1cd1',
    storageBucket: 'ux-design-e1cd1.appspot.com',
    iosBundleId: 'com.foxapps.app.uxDesignNovo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsgsO6JTEpfJKJPGkOn-fm07wXVFfMum4',
    appId: '1:696086497678:ios:1d71a5b3b49b02fd16fcdf',
    messagingSenderId: '696086497678',
    projectId: 'ux-design-e1cd1',
    storageBucket: 'ux-design-e1cd1.appspot.com',
    iosBundleId: 'com.foxapps.app.uxDesignNovo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6gOFisTQNEwHREZEgmE6BTrFq2gn6O1U',
    appId: '1:696086497678:web:67b62bb40be6c6c616fcdf',
    messagingSenderId: '696086497678',
    projectId: 'ux-design-e1cd1',
    authDomain: 'ux-design-e1cd1.firebaseapp.com',
    storageBucket: 'ux-design-e1cd1.appspot.com',
  );
}
